# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/07-Databases

dev:
  propel:
    param:
      classname:  DebugPDO
      debug:
        realmemoryusage: true
        details:
          time:       { enabled: true }
          slow:       { enabled: true, threshold: 0.1 }
          mem:        { enabled: true }
          mempeak:    { enabled: true }
          memdelta:   { enabled: true }

test:
  propel:
    param:
      classname:  DebugPDO
      dsn:        mysql:dbname=bookstore;host=127.0.0.1
      username:   bookstore
      password:   qTdzNVrKeZK5BwAr

  icepique:
    param:
      classname:  DebugPDO
      dsn:        mysql:dbname=bookstore;host=127.0.0.1
      username:   bookstore
      password:   qTdzNVrKeZK5BwAr

all:
  propel:
    class:        sfPropelDatabase
    param:
      classname:  PropelPDO
      dsn:        mysql:dbname=bookstore;host=127.0.0.1
      username:   bookstore
      password:   qTdzNVrKeZK5BwAr
      encoding:   utf8
      persistent: false
      pooling:    true

  icepique:
    class:        sfPropelDatabase
    param:
      classname:  PropelPDO
      dsn:        mysql:dbname=bookstore;host=127.0.0.1
      username:   bookstore
      password:   qTdzNVrKeZK5BwAr
      encoding:   utf8
      persistent: false
      pooling:    true
